"""initial

Revision ID: e504be5b9048
Revises: 
Create Date: 2025-06-01 17:34:40.262835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e504be5b9048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'processing', 'success', 'failure', name='statusenum').create(op.get_bind())
    op.create_table('parse_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'success', 'failure', name='statusenum', create_type=False), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('html_content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_requests')
    sa.Enum('pending', 'processing', 'success', 'failure', name='statusenum').drop(op.get_bind())
    # ### end Alembic commands ###
